// File generated by FlutterFire CLI.
// Run: flutterfire configure
// to replace this file with your real Firebase project configuration.
//
// ⚠️  IMPORTANT: Replace this placeholder before running on a device.
// Follow the Firebase setup steps in SETUP.md.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run: flutterfire configure',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR3wY5bcsX5LuTHYnDLItSTl2dhBTkag8',
    appId: '1:145576681864:android:21de0bbe543b9eace3da3d',
    messagingSenderId: '145576681864',
    projectId: 'sigap-901d8',
    storageBucket: 'sigap-901d8.firebasestorage.app',
  );

  // ── REPLACE THE VALUES BELOW WITH YOUR REAL FIREBASE CONFIG ──────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDXy0YLPNxXuclCpHfI-1wAghBGFnNIzA',
    appId: '1:145576681864:ios:7c015c6c0de1aae5e3da3d',
    messagingSenderId: '145576681864',
    projectId: 'sigap-901d8',
    storageBucket: 'sigap-901d8.firebasestorage.app',
    iosBundleId: 'com.sigap.sigap',
  );

}